### ISSUE TITLE
Plz no to use shorttags

### ISSUE THREAD

**Issue by georgestephanis** [MikeiLL/mz-mobilize-america-interface#1]
https://github.com/MikeiLL/mobilize-america/blob/92ebd31f8a49f57089416203b397af938e44bbc9/inc/frontend/views/event.php#L25

This breaks on some server configs.

**Comment by MikeiLL** [comment]
Hey bro. Somehow I missed this issue. Sorry, amigo and thanks for pointing that out. I don’t know how that single shortag got in there but it’s resolved now. Not that you would necessarily still be using this, two years later. I’m thinking of releasing it in WP Plugins repo.
